######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 15 12:46:37 2016
######################################################################

TEMPLATE = app
TARGET = rpn
INCLUDEPATH += .

# Input
HEADERS += rpn.h version.h
SOURCES += rpn.cc
