# RPN Tests Makefile
# jsp Sat Feb  7 21:59:34 CST 2009

CCFILES=$(shell ls -1 *.cc)
TARGETS=$(basename $(CCFILES))
INCLUDEPATH=.. ../../horny_toad
DEPENDPATH=.. ../../horny_toad
EXTRA_SOURCES=
LIBS=

include ../../Makefile.tests
