# RPN Tests Makefile
# jsp Sat Feb  7 21:59:34 CST 2009

CCFILES=$(shell ls -1 *.cc)
TARGETS=$(basename $(CCFILES))
INCLUDEPATH=.. ../../argv
DEPENDPATH=.. ../../argv
EXTRA_SOURCES=
LIBS=

include ../../qt_support/Makefile.tests
