######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 7 22:02:06 2009
######################################################################

TEMPLATE = app
TARGET = test_rpn
INCLUDEPATH += .

# Input
SOURCES += test_rpn.cc
